### ISSUE TITLE
Getting push payload

### ISSUE THREAD

**Issue by ilionic** [este/este-firebase#3]
How can I get unique id generated by `firebase.push` ? 
Before I could simply call `key()` on firebase reference after `push`, but in current implementation promise doesn't return anything, though entry on Firebase is created.
Thanks.

```
firebase.push(['path'], '')
    .then((payload) => {
        //payload empty
    });
```

**Comment by steida** [comment]
I am not using autogenerated ids so I don't know now. You can update code ofc.
